### PR TITLE
Clean up and fix docker

### LINKED ISSUE #502: Error starting Docker rai_node on latest Docker edge version
**Description of bug:**

Docker run command on latest Docker edge (Version 17.12.0-ce-mac45 (21669)) on MacOS fails with the following error:

```
$ sudo docker run -d -p 7075:7075/udp -p 7075:7075 -p [::1]:7076:7076 -v ~:/root clemahieu/rai_node /rai_node --daemon
Password:
ea29924038cf1eca3ea9ec45211fb7d194ea9d6bd53dddd9f35767968e56adc4
docker: Error response from daemon: driver failed programming external connectivity on endpoint eloquent_pasteur (53649cea89f42738f61d88198ddee3ff3a411e6611db96aff368630eeb128018): Error starting userland proxy: port is not a proto:IP:port: 'tcp:[:'.
```

**Steps to reproduce the issue:**

1. Install Docker Edge on MacOS
2. Run `sudo docker run -d -p 7075:7075/udp -p 7075:7075 -p [::1]:7076:7076 -v ~:/root `

**Describe the results you received:**

Error message: `Error starting userland proxy: port is not a proto:IP:port: 'tcp:[:'.`

**Describe the results you expected:**

The container should start.

**Additional information you deem important (e.g. issue happens only occasionally):**

The latest Docker seems to have a lot of fixes for vpnkit and proxy settings. I'm guessing something got broken here.

**Environment:**

- OS: MacOS Sierra
- Node version: clemahieu/rai_node:latest
- (docker node): Docker version 17.12.0-ce, build c97c6d6

**logs**

No logs, container doesn't start.

### PR DESCRIPTION
**Pull request by elliottneilclark**
Don't try and copy .so as rai_node is static.
Put default json config in docker.
Add entry point for cmd
Clean up the dockerfile to have fewer build steps

This should fix #502 but will need to change the wiki once it's in and the new docker image is published.

### CODE REVIEW

**Comment by PlasmaPower** [comment]
I'd move `/config.json` somewhere else, as people might edit it thinking they are editing the config.

**Comment by elliottneilclark** [comment]
How does /usr/share/raiblocks/ sound ?

**Comment by PlasmaPower** [comment]
Sure

On Jan 25, 2018 6:16 PM, "Elliott" <notifications@github.com> wrote:

How does /usr/share/raiblocks/ sound ?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/clemahieu/raiblocks/pull/546#issuecomment-360654982>,
or mute the thread

**Comment by PlasmaPower** [comment]
Anything wrong with this PR? @androm3da @lukealonso

File: docker/node/entry.sh [hunk 1]
```diff
@@ -0,0 +1,10 @@
+#!/bin/bash
+set -euo pipefail
+IFS=$'\n\t'
+
+mkdir -p ~/RaiBlocks
+if [ ! -f ~/RaiBlocks/config.json ]; then
+  echo "Config File not found, adding default."
+  cp /usr/share/raiblocks/config.json ~/RaiBlocks/
```
Comment (androm3da) [inline docker/node/entry.sh]: Isn't this the `node`'s existing default behavior?  Why reproduce it here?

Comment (PlasmaPower) [reply docker/node/entry.sh]: The default config here listens on IPv4, not IPv6, because Docker only works with the former.

Comment (PlasmaPower) [reply docker/node/entry.sh]: It also enables the RPC. You can view the `config.json` file in this PR for more details.

Comment (androm3da) [reply docker/node/entry.sh]: It's a shame that it's another maintenance item but I see why it's needed now.
